"""Criando tabela Produto

Revision ID: 34305ce2b0c3
Revises: 
Create Date: 2025-04-09 09:48:14.899823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34305ce2b0c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_product', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_product')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
